dist: trusty
sudo: required

language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

install:
 - 'if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
        sudo apt-get install libyajl-dev;
        sudo apt-get install libev-libevent-dev;
        sudo apt-get install libpcre3-dev;
    fi'
 - 'if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
        brew install yajl;
        brew install libevent;
        brew install pcre;
    fi'


before_script:
  - mkdir build
  - cd build

script:
  - cmake ..
  - make
  - ./_build/binaries/io ../libs/iovm/tests/correctness/run.io
